<a href="https://colab.research.google.com/github/DLPY/Classification_Session_2/blob/main/Student_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/DLPY/Classification_Session_2/main/Student2020.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1131 entries, 0 to 1130
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   age                  1131 non-null   int64
 1   Auditory             1131 non-null   float64
 2   Kinaesthetic         1131 non-null   float64
 3   Visual               1131 non-null   float64
 4   ExtrinsicMotivation  1131 non-null   float64
 5   IntrinsicMotivation  1131 non-null   float64
 6   SelfEfficacy         1131 non-null   float64
 7   StudyTime            1131 non-null   float64
 8   Conscientiousness    1131 non-null   float64
 9   CAOpoints            1131 non-null   int64
 10  Maths                1131 non-null   int64
 11  English              1131 non-null   int64
 12  Pass                 1131 non-null   object
dtypes: float64(8), int64(4), object(1)
memory usage: 115.0+ KB

In [ ]:
df.describe()

               age     Auditory  ...        Maths      English
count  1131.000000  1131.000000  ...  1131.000000  1131.000000
mean     23.398762     3.351526  ...    35.271441    42.763926
std       5.996987     1.699769  ...    23.337077    23.936272
min      18.000000     0.000000  ...     0.000000     0.000000
25%      19.000000     2.500000  ...    16.000000    25.000000
50%      21.000000     2.911785  ...    35.000000    44.000000
75%      26.000000     4.637668  ...    54.000000    62.500000
max      59.000000     9.408472  ...   100.000000   100.000000

[8 rows x 12 columns]

In [ ]:
X = df.drop(['Pass'], axis =1)
y = df['Pass']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=5)
knn = neigh.fit(X_train, y_train)

In [ ]:
y_pred = knn.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import classification_report
target_names = ['Pass', 'Fail']
print(classification_report(y_test, y_pred, target_names=target_names))

[[ 60  77]
 [ 51 186]]
              precision    recall  f1-score   support

        Pass       0.54      0.44      0.48       137
        Fail       0.71      0.78      0.74       237

    accuracy                           0.66       374
   macro avg       0.62      0.61      0.61       374
weighted avg       0.65      0.66      0.65       374

In [ ]:
# Scale Data

from sklearn import preprocessing
scale_X = preprocessing.normalize(X)
scaled_X = pd.DataFrame(scale_X, columns=X.columns)
scaled_X.head()

        age  Auditory  Kinaesthetic  ...  CAOpoints     Maths   English
0  0.053304  0.014027      0.018792  ...   0.987518  0.053304  0.126245
1  0.158487  0.032135      0.012781  ...   0.956034  0.178937  0.143150
2  0.297045  0.055918      0.020628  ...   0.915888  0.173276  0.140271
3  0.066023  0.020276      0.011967  ...   0.981348  0.108038  0.138049
4  0.082265  0.025855      0.007971  ...   0.980024  0.118032  0.125186

[5 rows x 12 columns]

In [ ]:
# Scaled Example at k = 5

X_train, X_test, y_train, y_test = train_test_split(scaled_X, y, test_size=0.33, random_state=42)
neigh = KNeighborsClassifier(n_neighbors=5)
knn = neigh.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print(classification_report(y_test, y_pred, target_names=target_names))
confusion_matrix(y_test, y_pred)

              precision    recall  f1-score   support

        Pass       0.69      0.55      0.61       137
        Fail       0.77      0.86      0.81       237

    accuracy                           0.74       374
   macro avg       0.73      0.70      0.71       374
weighted avg       0.74      0.74      0.74       374

array([[ 75,  62],
       [ 34, 203]])

In [ ]:
# Searching parameter outcomes using a for loop

for x in [1,3,5,7,9,11,13]:
  neigh = KNeighborsClassifier(n_neighbors=x)
  knn = neigh.fit(X_train, y_train)
  y_pred = knn.predict(X_test)
  print(f"The value of K = {x}")
  print(classification_report(y_test, y_pred, target_names=target_names))

The value of K = 1
              precision    recall  f1-score   support

        Pass       0.66      0.64      0.65       137
        Fail       0.79      0.81      0.80       237

    accuracy                           0.75       374
   macro avg       0.73      0.72      0.72       374
weighted avg       0.74      0.75      0.74       374

The value of K = 3
              precision    recall  f1-score   support

        Pass       0.67      0.58      0.62       137
        Fail       0.78      0.83      0.80       237

    accuracy                           0.74       374
   macro avg       0.72      0.71      0.71       374
weighted avg       0.74      0.74      0.74       374

The value of K = 5
              precision    recall  f1-score   support

        Pass       0.69      0.55      0.61       137
        Fail       0.77      0.86      0.81       237

    accuracy                           0.74       374
   macro avg       0.73      0.70      0.71       374
weighted avg       0.74      0.74      0.74       374

The value of K = 7
              precision    recall  f1-score   support

        Pass       0.65      0.51      0.57       137
        Fail       0.75      0.84      0.79       237

    accuracy                           0.72       374
   macro avg       0.70      0.68      0.68       374
weighted avg       0.71      0.72      0.71       374

The value of K = 9
              precision    recall  f1-score   support

        Pass       0.67      0.48      0.56       137
        Fail       0.74      0.86      0.80       237

    accuracy                           0.72       374
   macro avg       0.70      0.67      0.68       374
weighted avg       0.71      0.72      0.71       374

The value of K = 11
              precision    recall  f1-score   support

        Pass       0.64      0.43      0.52       137
        Fail       0.72      0.86      0.79       237

    accuracy                           0.70       374
   macro avg       0.68      0.65      0.65       374
weighted avg       0.69      0.70      0.69       374

The value of K = 13
              precision    recall  f1-score   support

        Pass       0.61      0.43      0.50       137
        Fail       0.72      0.84      0.77       237

    accuracy                           0.69       374
   macro avg       0.66      0.64      0.64       374
weighted avg       0.68      0.69      0.68       374

In [ ]:
# Grid Search

from sklearn.model_selection import GridSearchCV

grid_params = {
    'n_neighbors' : [1,3,5,7,9,11,13],
    'weights' : ['uniform','distance'],
    'metric' : ['euclidean','manhattan']
}

gs = GridSearchCV(
  KNeighborsClassifier(),
  grid_params, 
  cv = 3, # cross validation to try for each set of parameters
  n_jobs = -1, # number of processors -1 will use all avaliable
  verbose = 1 # detailed print out
)

gs_results = gs.fit(X_train, y_train)

Fitting 3 folds for each of 28 candidates, totalling 84 fits
GridSearchCV(cv=3, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'metric': ['euclidean', 'manhattan'],
                         'n_neighbors': [1, 3, 5, 7, 9, 11, 13],
                         'weights': ['uniform', 'distance']},
             verbose=1)

In [ ]:
# Best Parameters

print(gs_results.best_score_)
print(gs_results.best_estimator_)
print(gs_results.best_params_)

grid_predictions = gs.predict(X_test)

print(classification_report(y_test, grid_predictions))

0.7424190141581445
KNeighborsClassifier(metric='manhattan', weights='distance')
{'metric': 'manhattan', 'n_neighbors': 5, 'weights': 'distance'}
              precision    recall  f1-score   support

        Fail       0.74      0.63      0.68       137
        Pass       0.80      0.87      0.83       237

    accuracy                           0.78       374
   macro avg       0.77      0.75      0.76       374
weighted avg       0.78      0.78      0.78       374