<a href="https://colab.research.google.com/github/DLPY/Classification_Session_2/blob/main/Student_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/DLPY/Classification_Session_2/main/Student2020.csv')

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1131 entries, 0 to 1130
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   age                  1131 non-null   int64
 1   Auditory             1131 non-null   float64
 2   Kinaesthetic         1131 non-null   float64
 3   Visual               1131 non-null   float64
 4   ExtrinsicMotivation  1131 non-null   float64
 5   IntrinsicMotivation  1131 non-null   float64
 6   SelfEfficacy         1131 non-null   float64
 7   StudyTime            1131 non-null   float64
 8   Conscientiousness    1131 non-null   float64
 9   CAOpoints            1131 non-null   int64
 10  Maths                1131 non-null   int64
 11  English              1131 non-null   int64
 12  Pass                 1131 non-null   object
dtypes: float64(8), int64(4), object(1)
memory usage: 115.0+ KB

In [37]:
df.describe()

               age     Auditory  ...        Maths      English
count  1131.000000  1131.000000  ...  1131.000000  1131.000000
mean     23.398762     3.351526  ...    35.271441    42.763926
std       5.996987     1.699769  ...    23.337077    23.936272
min      18.000000     0.000000  ...     0.000000     0.000000
25%      19.000000     2.500000  ...    16.000000    25.000000
50%      21.000000     2.911785  ...    35.000000    44.000000
75%      26.000000     4.637668  ...    54.000000    62.500000
max      59.000000     9.408472  ...   100.000000   100.000000

[8 rows x 12 columns]

In [38]:
X = df.drop(['Pass'], axis =1)
y = df['Pass']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [39]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=5)
knn = neigh.fit(X_train, y_train)

In [40]:
y_pred = knn.predict(X_test)

In [41]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import classification_report
target_names = ['Pass', 'Fail']
print(classification_report(y_test, y_pred, target_names=target_names))

[[ 60  77]
 [ 51 186]]
              precision    recall  f1-score   support

        Pass       0.54      0.44      0.48       137
        Fail       0.71      0.78      0.74       237

    accuracy                           0.66       374
   macro avg       0.62      0.61      0.61       374
weighted avg       0.65      0.66      0.65       374

In [42]:
# Scale Data

from sklearn import preprocessing
trans = preprocessing.MinMaxScaler(feature_range=(-1,1))
scaled_X = pd.DataFrame(trans.fit_transform(X))
scaled_X.head()

         0         1         2         3   ...        8       9     10    11
0 -0.951220  0.062872  0.356470 -0.384994  ...  0.662943  0.1264 -0.62 -0.10
1 -0.365854  0.336144 -0.493733  0.217283  ...  0.040436 -0.4016 -0.30 -0.44
2 -0.121951  0.440609 -0.493733  0.115672  ... -0.026629 -0.6448 -0.58 -0.66
3 -0.804878  0.436180 -0.192456 -0.187632  ... -0.614036  0.0464 -0.28 -0.08
4 -0.756098  0.536627 -0.548682  0.078383  ... -0.481451 -0.1232 -0.34 -0.30

[5 rows x 12 columns]

In [43]:
# Scaled Example at k = 5

X_train, X_test, y_train, y_test = train_test_split(scaled_X, y, test_size=0.33, random_state=42)
neigh = KNeighborsClassifier(n_neighbors=5)
knn = neigh.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print(classification_report(y_test, y_pred, target_names=target_names))
confusion_matrix(y_test, y_pred)

              precision    recall  f1-score   support

        Pass       0.82      0.74      0.78       137
        Fail       0.86      0.90      0.88       237

    accuracy                           0.84       374
   macro avg       0.84      0.82      0.83       374
weighted avg       0.84      0.84      0.84       374

array([[102,  35],
       [ 23, 214]])

In [44]:
# Searching parameter outcomes using a for loop

for x in [5,10,15,25,30,35]:
  neigh = KNeighborsClassifier(n_neighbors=x)
  knn = neigh.fit(X_train, y_train)
  y_pred = knn.predict(X_test)
  print(f"The value of K = {x}")
  print(classification_report(y_test, y_pred, target_names=target_names))

The value of K = 5
              precision    recall  f1-score   support

        Pass       0.82      0.74      0.78       137
        Fail       0.86      0.90      0.88       237

    accuracy                           0.84       374
   macro avg       0.84      0.82      0.83       374
weighted avg       0.84      0.84      0.84       374

The value of K = 10
              precision    recall  f1-score   support

        Pass       0.76      0.72      0.74       137
        Fail       0.84      0.86      0.85       237

    accuracy                           0.81       374
   macro avg       0.80      0.79      0.80       374
weighted avg       0.81      0.81      0.81       374

The value of K = 15
              precision    recall  f1-score   support

        Pass       0.77      0.60      0.67       137
        Fail       0.79      0.89      0.84       237

    accuracy                           0.79       374
   macro avg       0.78      0.75      0.76       374
weighted avg       0.78      0.79      0.78       374

The value of K = 25
              precision    recall  f1-score   support

        Pass       0.75      0.47      0.58       137
        Fail       0.75      0.91      0.82       237

    accuracy                           0.75       374
   macro avg       0.75      0.69      0.70       374
weighted avg       0.75      0.75      0.73       374

The value of K = 30
              precision    recall  f1-score   support

        Pass       0.70      0.47      0.56       137
        Fail       0.74      0.89      0.81       237

    accuracy                           0.73       374
   macro avg       0.72      0.68      0.68       374
weighted avg       0.73      0.73      0.72       374

The value of K = 35
              precision    recall  f1-score   support

        Pass       0.68      0.36      0.47       137
        Fail       0.71      0.90      0.79       237

    accuracy                           0.70       374
   macro avg       0.69      0.63      0.63       374
weighted avg       0.70      0.70      0.67       374

In [45]:
# Grid Search

from sklearn.model_selection import GridSearchCV

grid_params = {
    'n_neighbors' : [1,3,5,7,9,11,13,15,17,19,21,22,24,26,28,30,32,34],
    'weights' : ['uniform','distance'],
    'metric' : ['euclidean','manhattan']
}

gs = GridSearchCV(
  KNeighborsClassifier(),
  grid_params, 
  cv = 3, # cross validation to try for each set of parameters
  n_jobs = -1, # number of processors -1 will use all avaliable
  verbose = 1 # detailed print out
)

gs_results = gs.fit(X_train, y_train)

Fitting 3 folds for each of 72 candidates, totalling 216 fits

In [46]:
# Best Parameters

print(gs_results.best_score_)
print(gs_results.best_estimator_)
print(gs_results.best_params_)

grid_predictions = gs.predict(X_test)

print(classification_report(y_test, grid_predictions))

0.7978700043917435
KNeighborsClassifier(metric='manhattan', weights='distance')
{'metric': 'manhattan', 'n_neighbors': 5, 'weights': 'distance'}
              precision    recall  f1-score   support

        Fail       0.86      0.74      0.79       137
        Pass       0.86      0.93      0.89       237

    accuracy                           0.86       374
   macro avg       0.86      0.83      0.84       374
weighted avg       0.86      0.86      0.86       374